versions: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt

  build:
    commands:
      - echo Build started on `date`
      - python -c "import flask; print('Flask import OK')"
      - echo Build completed successfully!

artifacts:
  files:
    - '**/*'
  discard-paths: no